AllowedHosts = "*"

[Logging.LogLevel]
Default = "Warning"
"Net.Vatprc" = "Information"
"Program" = "Information"
"Microsoft.Hosting.Lifetime" = "Information"
"Microsoft.AspNetCore.Hosting.Diagnostics" = "Information"

[ConnectionStrings]
VATPRCContext = "Host=localhost;Database=uniapi;Include Error Detail=true"

[Authentication.Jwt]
# Generate ECC key with https://dinochiesa.github.io/jwt/
PrivateKey = """
-----BEGIN PRIVATE KEY-----
......
-----END PRIVATE KEY-----
"""
PublicKey = """
-----BEGIN PUBLIC KEY-----
......
-----END PUBLIC KEY-----
"""
Issuer = "https://uniapi.vatprc.net"
AudienceFirstParty = "https://uniapi.vatprc.net"
FirstPartyExpires = 01:00:00
RefreshExpiresDays = 7
DeviceAuthzExpires = 3600

[Authentication.Vatsim]
Endpoint = "https://auth.vatsim.net"
ClientId = ""
ClientSecret = ""
RedirectUri = "https://example.com/auth/callback/vatsim"

[Authentication.Internal.VatprcAtcService]
Endpoint = "https://atcapi.vatprc.net"
TokenAudience = "https://atcapi.vatprc.net"
# Generate ECC key with https://dinochiesa.github.io/jwt/
PrivateKey = """
-----BEGIN PRIVATE KEY-----
......
-----END PRIVATE KEY-----
"""
PublicKey = """
-----BEGIN PUBLIC KEY-----
......
-----END PUBLIC KEY-----
"""

[Discourse]
Endpoint = "https://community.vatprc.net"
ApiKey = ""

[Storage.Image.Smms]
SecretToken = ""

[Navdata.Arinc424]
ServiceUrl = ""
AccessKey = ""
SecretKey = ""
Bucket = ""
ArincPath = ""
